name: Build beamer presentation
run-name: ${{ github.actor }} is building the presentation
on: [push]
jobs:
  build-presentation-on-container:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          mkdir output
          pandoc -s --dpi=300 --slide-level 2 --toc --listings --shift-heading-level=0 --columns=50 --template default_mod.latex --pdf-engine lualatex -f "$SOURCE_FORMAT" -M date="$DATE_COVER" -V classoption:aspectratio=169 -V lang=en-AU -t beamer README.md -o output/preso.pdf
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: presentation
          path: |
            output